- type: local
  path: /home/manuel/Downloads/diff-review.jsx
  lastFetched: 2026-04-27T17:41:15.666823562-04:00
- type: local
  path: /home/manuel/code/wesen/2026-04-23--pyxis/ttmp/2026/04/27/PYXIS-APP-VISUAL-TUNING--pyxis-app-visual-tuning-topbar-dashboard-new-pages/reference/05-public-pages-review-site-analysis-and-guide.md
  lastFetched: 2026-04-27T17:41:22.295540508-04:00
