// Code generated by logcopter-gen; DO NOT EDIT.

package provider

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.css-visual-diff.pkg.xgoja.provider")
