// Code generated by logcopter-gen; DO NOT EDIT.

package service

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.css-visual-diff.internal.cssvisualdiff.service")
